// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8YM6Q9TzrMKysSrdillHLI8GLPbcstb0',
    appId: '1:535911339466:web:8218525427eb9974ae6b33',
    messagingSenderId: '535911339466',
    projectId: 'gcp-test-428701',
    authDomain: 'gcp-test-428701.firebaseapp.com',
    storageBucket: 'gcp-test-428701.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4R0nlbj3wNRHFEyx3MEwFmpuL13CdvLA',
    appId: '1:535911339466:ios:ebae7c061beeb612ae6b33',
    messagingSenderId: '535911339466',
    projectId: 'gcp-test-428701',
    storageBucket: 'gcp-test-428701.appspot.com',
    iosBundleId: 'com.example.dalVacationHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8YM6Q9TzrMKysSrdillHLI8GLPbcstb0',
    appId: '1:535911339466:web:135ee540d9aad348ae6b33',
    messagingSenderId: '535911339466',
    projectId: 'gcp-test-428701',
    authDomain: 'gcp-test-428701.firebaseapp.com',
    storageBucket: 'gcp-test-428701.appspot.com',
  );
}
